language: go

env:
  global:
    - GO111MODULE=on

script:
  - go get golang.org/x/tools/cmd/gopls
  - go get github.com/sourcegraph/go-langserver
  - sudo pip install 'python-language-server[yapf]'
  - go install -v ./...
  - test `gofmt -l . | wc -l` = 0
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...
  - GOOS=plan9 go build ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
