on: [push]
name: Test

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    env:
      GO111MODULE: on

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Check gofmt
      run: |
        sudo modprobe kvm
        ls -l /dev/kvm
        id
        docker run --rm -t --device /dev/kvm:/dev/kvm fshahriar/plan9go:1.14.1-front.1 go version
      shell: bash
